version: '3'
services:
  mongo-primary:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 5m
    ports:
      - "${MONGO_PRIMARY_PORT}:27017"
    volumes:
      - "${MONGO_PRIMARY_DB_PATH}:/data/db"
      - "${MONGO_CONF_PATH}:/etc/mongod.conf:ro"
  mongo-secondary:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 5m
    depends_on:
      - "mongo-primary"
    ports:
      - "${MONGO_SECONDARY_PORT}:27017"
    volumes:
      - "${MONGO_SECONDARY_DB_PATH}:/data/db"
      - "${MONGO_CONF_PATH}:/etc/mongod.conf:ro"
  mongo-arbiter:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 5m
    ports:
      - "${MONGO_ARBITER_PORT}:27017"
    command: "mongod --syslog --replSet ${MONGO_REPLSET}"
